//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmexSrv
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmexSrv.EmExServiceSoap")]
    public interface EmExServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindDetailAdv4", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EmexSrv.FindDetailAdv4Response> FindDetailAdv4Async(EmexSrv.FindDetailAdv4Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindDetailAdv5", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EmexSrv.FindDetailAdv5Response> FindDetailAdv5Async(EmexSrv.FindDetailAdv5Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindDetailAdv4_Test", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EmexSrv.SoapSearchResult> FindDetailAdv4_TestAsync(long login, string password, string makeLogo, string detailNum, EmexSrv.SearchSubstLevel substLevel, EmexSrv.SearchSubstFilter substFilter, EmexSrv.FindDeliveryRegionType deliveryRegionType, string minDeliveryPercentString, string maxADDaysString, string minQuantityString, string maxResultPriceString, string maxOneDetailOffersCountString, string detailNumsToLoadString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindDetailAdv5_Test", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EmexSrv.SearchResult> FindDetailAdv5_TestAsync(long login, string password, string makeLogo, string detailNum, EmexSrv.SearchSubstLevel substLevel, EmexSrv.SearchSubstFilter substFilter, EmexSrv.FindDeliveryRegionType deliveryRegionType, string minDeliveryPercentString, string maxADDaysString, string minQuantityString, string maxResultPriceString, string maxOneDetailOffersCountString, string detailNumsToLoadString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestConnect", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> TestConnectAsync(string s);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SearchSubstLevel
    {
        
        /// <remarks/>
        OriginalOnly,
        
        /// <remarks/>
        All,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SearchSubstFilter
    {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        FilterOriginalAndReplacements,
        
        /// <remarks/>
        FilterOriginalAndAnalogs,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum FindDeliveryRegionType
    {
        
        /// <remarks/>
        PRI,
        
        /// <remarks/>
        ALT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SoapSearchResult
    {
        
        private SoapDetailItem[] detailsField;
        
        private bool isSuccessField;
        
        private string errorMessageField;
        
        private System.Nullable<System.DateTime> blockDateEndField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public SoapDetailItem[] Details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool IsSuccess
        {
            get
            {
                return this.isSuccessField;
            }
            set
            {
                this.isSuccessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> BlockDateEnd
        {
            get
            {
                return this.blockDateEndField;
            }
            set
            {
                this.blockDateEndField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SoapDetailItem
    {
        
        private int groupIdField;
        
        private PriceGroup priceGroupField;
        
        private string makeLogoField;
        
        private string makeNameField;
        
        private string detailNumField;
        
        private string newDetailNumField;
        
        private string detailNameRusField;
        
        private string priceLogoField;
        
        private string destinationLogoField;
        
        private string priceCountryField;
        
        private int lotQuantityField;
        
        private System.Nullable<int> quantityField;
        
        private decimal dDPercentField;
        
        private int aDDaysField;
        
        private int deliverTimeGuaranteedField;
        
        private decimal resultPriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int GroupId
        {
            get
            {
                return this.groupIdField;
            }
            set
            {
                this.groupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PriceGroup PriceGroup
        {
            get
            {
                return this.priceGroupField;
            }
            set
            {
                this.priceGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MakeLogo
        {
            get
            {
                return this.makeLogoField;
            }
            set
            {
                this.makeLogoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MakeName
        {
            get
            {
                return this.makeNameField;
            }
            set
            {
                this.makeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DetailNum
        {
            get
            {
                return this.detailNumField;
            }
            set
            {
                this.detailNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NewDetailNum
        {
            get
            {
                return this.newDetailNumField;
            }
            set
            {
                this.newDetailNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DetailNameRus
        {
            get
            {
                return this.detailNameRusField;
            }
            set
            {
                this.detailNameRusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string PriceLogo
        {
            get
            {
                return this.priceLogoField;
            }
            set
            {
                this.priceLogoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string DestinationLogo
        {
            get
            {
                return this.destinationLogoField;
            }
            set
            {
                this.destinationLogoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string PriceCountry
        {
            get
            {
                return this.priceCountryField;
            }
            set
            {
                this.priceCountryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int LotQuantity
        {
            get
            {
                return this.lotQuantityField;
            }
            set
            {
                this.lotQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<int> Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal DDPercent
        {
            get
            {
                return this.dDPercentField;
            }
            set
            {
                this.dDPercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int ADDays
        {
            get
            {
                return this.aDDaysField;
            }
            set
            {
                this.aDDaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int DeliverTimeGuaranteed
        {
            get
            {
                return this.deliverTimeGuaranteedField;
            }
            set
            {
                this.deliverTimeGuaranteedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public decimal ResultPrice
        {
            get
            {
                return this.resultPriceField;
            }
            set
            {
                this.resultPriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum PriceGroup
    {
        
        /// <remarks/>
        und,
        
        /// <remarks/>
        Stoc,
        
        /// <remarks/>
        Original,
        
        /// <remarks/>
        NewNumber,
        
        /// <remarks/>
        ReplacementOriginal,
        
        /// <remarks/>
        ReplacementNonOriginal,
        
        /// <remarks/>
        PartOfDetail,
        
        /// <remarks/>
        DetailParts,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DetailItem
    {
        
        private int groupIdField;
        
        private PriceGroup priceGroupField;
        
        private string makeLogoField;
        
        private string makeNameField;
        
        private string detailNumField;
        
        private string newDetailNumField;
        
        private string detailNameRusField;
        
        private string priceLogoField;
        
        private string destinationLogoField;
        
        private string priceCountryField;
        
        private int lotQuantityField;
        
        private System.Nullable<int> quantityField;
        
        private decimal dDPercentField;
        
        private int aDDaysField;
        
        private decimal resultPriceField;
        
        private string deliveryRegionTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int GroupId
        {
            get
            {
                return this.groupIdField;
            }
            set
            {
                this.groupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PriceGroup PriceGroup
        {
            get
            {
                return this.priceGroupField;
            }
            set
            {
                this.priceGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MakeLogo
        {
            get
            {
                return this.makeLogoField;
            }
            set
            {
                this.makeLogoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MakeName
        {
            get
            {
                return this.makeNameField;
            }
            set
            {
                this.makeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DetailNum
        {
            get
            {
                return this.detailNumField;
            }
            set
            {
                this.detailNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NewDetailNum
        {
            get
            {
                return this.newDetailNumField;
            }
            set
            {
                this.newDetailNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DetailNameRus
        {
            get
            {
                return this.detailNameRusField;
            }
            set
            {
                this.detailNameRusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string PriceLogo
        {
            get
            {
                return this.priceLogoField;
            }
            set
            {
                this.priceLogoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string DestinationLogo
        {
            get
            {
                return this.destinationLogoField;
            }
            set
            {
                this.destinationLogoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string PriceCountry
        {
            get
            {
                return this.priceCountryField;
            }
            set
            {
                this.priceCountryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int LotQuantity
        {
            get
            {
                return this.lotQuantityField;
            }
            set
            {
                this.lotQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<int> Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal DDPercent
        {
            get
            {
                return this.dDPercentField;
            }
            set
            {
                this.dDPercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int ADDays
        {
            get
            {
                return this.aDDaysField;
            }
            set
            {
                this.aDDaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public decimal ResultPrice
        {
            get
            {
                return this.resultPriceField;
            }
            set
            {
                this.resultPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string DeliveryRegionType
        {
            get
            {
                return this.deliveryRegionTypeField;
            }
            set
            {
                this.deliveryRegionTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchResult
    {
        
        private DetailItem[] detailsField;
        
        private bool isSuccessField;
        
        private string errorMessageField;
        
        private System.Nullable<System.DateTime> blockDateEndField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public DetailItem[] Details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool IsSuccess
        {
            get
            {
                return this.isSuccessField;
            }
            set
            {
                this.isSuccessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> BlockDateEnd
        {
            get
            {
                return this.blockDateEndField;
            }
            set
            {
                this.blockDateEndField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindDetailAdv4", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindDetailAdv4Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string makeLogo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string detailNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public EmexSrv.SearchSubstLevel substLevel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public EmexSrv.SearchSubstFilter substFilter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public EmexSrv.FindDeliveryRegionType deliveryRegionType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> minDeliveryPercent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> maxADDays;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> minQuantity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> maxResultPrice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> maxOneDetailOffersCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public string[] detailNumsToLoad;
        
        public FindDetailAdv4Request()
        {
        }
        
        public FindDetailAdv4Request(long login, string password, string makeLogo, string detailNum, EmexSrv.SearchSubstLevel substLevel, EmexSrv.SearchSubstFilter substFilter, EmexSrv.FindDeliveryRegionType deliveryRegionType, System.Nullable<decimal> minDeliveryPercent, System.Nullable<int> maxADDays, System.Nullable<int> minQuantity, System.Nullable<decimal> maxResultPrice, System.Nullable<int> maxOneDetailOffersCount, string[] detailNumsToLoad)
        {
            this.login = login;
            this.password = password;
            this.makeLogo = makeLogo;
            this.detailNum = detailNum;
            this.substLevel = substLevel;
            this.substFilter = substFilter;
            this.deliveryRegionType = deliveryRegionType;
            this.minDeliveryPercent = minDeliveryPercent;
            this.maxADDays = maxADDays;
            this.minQuantity = minQuantity;
            this.maxResultPrice = maxResultPrice;
            this.maxOneDetailOffersCount = maxOneDetailOffersCount;
            this.detailNumsToLoad = detailNumsToLoad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindDetailAdv4Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindDetailAdv4Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EmexSrv.SoapSearchResult FindDetailAdv4Result;
        
        public FindDetailAdv4Response()
        {
        }
        
        public FindDetailAdv4Response(EmexSrv.SoapSearchResult FindDetailAdv4Result)
        {
            this.FindDetailAdv4Result = FindDetailAdv4Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindDetailAdv5", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindDetailAdv5Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string makeLogo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string detailNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public EmexSrv.SearchSubstLevel substLevel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public EmexSrv.SearchSubstFilter substFilter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public EmexSrv.FindDeliveryRegionType deliveryRegionType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> minDeliveryPercent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> maxADDays;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> minQuantity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> maxResultPrice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> maxOneDetailOffersCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public string[] detailNumsToLoad;
        
        public FindDetailAdv5Request()
        {
        }
        
        public FindDetailAdv5Request(long login, string password, string makeLogo, string detailNum, EmexSrv.SearchSubstLevel substLevel, EmexSrv.SearchSubstFilter substFilter, EmexSrv.FindDeliveryRegionType deliveryRegionType, System.Nullable<decimal> minDeliveryPercent, System.Nullable<int> maxADDays, System.Nullable<int> minQuantity, System.Nullable<decimal> maxResultPrice, System.Nullable<int> maxOneDetailOffersCount, string[] detailNumsToLoad)
        {
            this.login = login;
            this.password = password;
            this.makeLogo = makeLogo;
            this.detailNum = detailNum;
            this.substLevel = substLevel;
            this.substFilter = substFilter;
            this.deliveryRegionType = deliveryRegionType;
            this.minDeliveryPercent = minDeliveryPercent;
            this.maxADDays = maxADDays;
            this.minQuantity = minQuantity;
            this.maxResultPrice = maxResultPrice;
            this.maxOneDetailOffersCount = maxOneDetailOffersCount;
            this.detailNumsToLoad = detailNumsToLoad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindDetailAdv5Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindDetailAdv5Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EmexSrv.SearchResult FindDetailAdv5Result;
        
        public FindDetailAdv5Response()
        {
        }
        
        public FindDetailAdv5Response(EmexSrv.SearchResult FindDetailAdv5Result)
        {
            this.FindDetailAdv5Result = FindDetailAdv5Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface EmExServiceSoapChannel : EmexSrv.EmExServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class EmExServiceSoapClient : System.ServiceModel.ClientBase<EmexSrv.EmExServiceSoap>, EmexSrv.EmExServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EmExServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(EmExServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), EmExServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmExServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EmExServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmExServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EmExServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmExServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmexSrv.FindDetailAdv4Response> EmexSrv.EmExServiceSoap.FindDetailAdv4Async(EmexSrv.FindDetailAdv4Request request)
        {
            return base.Channel.FindDetailAdv4Async(request);
        }
        
        public System.Threading.Tasks.Task<EmexSrv.FindDetailAdv4Response> FindDetailAdv4Async(long login, string password, string makeLogo, string detailNum, EmexSrv.SearchSubstLevel substLevel, EmexSrv.SearchSubstFilter substFilter, EmexSrv.FindDeliveryRegionType deliveryRegionType, System.Nullable<decimal> minDeliveryPercent, System.Nullable<int> maxADDays, System.Nullable<int> minQuantity, System.Nullable<decimal> maxResultPrice, System.Nullable<int> maxOneDetailOffersCount, string[] detailNumsToLoad)
        {
            EmexSrv.FindDetailAdv4Request inValue = new EmexSrv.FindDetailAdv4Request();
            inValue.login = login;
            inValue.password = password;
            inValue.makeLogo = makeLogo;
            inValue.detailNum = detailNum;
            inValue.substLevel = substLevel;
            inValue.substFilter = substFilter;
            inValue.deliveryRegionType = deliveryRegionType;
            inValue.minDeliveryPercent = minDeliveryPercent;
            inValue.maxADDays = maxADDays;
            inValue.minQuantity = minQuantity;
            inValue.maxResultPrice = maxResultPrice;
            inValue.maxOneDetailOffersCount = maxOneDetailOffersCount;
            inValue.detailNumsToLoad = detailNumsToLoad;
            return ((EmexSrv.EmExServiceSoap)(this)).FindDetailAdv4Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmexSrv.FindDetailAdv5Response> EmexSrv.EmExServiceSoap.FindDetailAdv5Async(EmexSrv.FindDetailAdv5Request request)
        {
            return base.Channel.FindDetailAdv5Async(request);
        }
        
        public System.Threading.Tasks.Task<EmexSrv.FindDetailAdv5Response> FindDetailAdv5Async(long login, string password, string makeLogo, string detailNum, EmexSrv.SearchSubstLevel substLevel, EmexSrv.SearchSubstFilter substFilter, EmexSrv.FindDeliveryRegionType deliveryRegionType, System.Nullable<decimal> minDeliveryPercent, System.Nullable<int> maxADDays, System.Nullable<int> minQuantity, System.Nullable<decimal> maxResultPrice, System.Nullable<int> maxOneDetailOffersCount, string[] detailNumsToLoad)
        {
            EmexSrv.FindDetailAdv5Request inValue = new EmexSrv.FindDetailAdv5Request();
            inValue.login = login;
            inValue.password = password;
            inValue.makeLogo = makeLogo;
            inValue.detailNum = detailNum;
            inValue.substLevel = substLevel;
            inValue.substFilter = substFilter;
            inValue.deliveryRegionType = deliveryRegionType;
            inValue.minDeliveryPercent = minDeliveryPercent;
            inValue.maxADDays = maxADDays;
            inValue.minQuantity = minQuantity;
            inValue.maxResultPrice = maxResultPrice;
            inValue.maxOneDetailOffersCount = maxOneDetailOffersCount;
            inValue.detailNumsToLoad = detailNumsToLoad;
            return ((EmexSrv.EmExServiceSoap)(this)).FindDetailAdv5Async(inValue);
        }
        
        public System.Threading.Tasks.Task<EmexSrv.SoapSearchResult> FindDetailAdv4_TestAsync(long login, string password, string makeLogo, string detailNum, EmexSrv.SearchSubstLevel substLevel, EmexSrv.SearchSubstFilter substFilter, EmexSrv.FindDeliveryRegionType deliveryRegionType, string minDeliveryPercentString, string maxADDaysString, string minQuantityString, string maxResultPriceString, string maxOneDetailOffersCountString, string detailNumsToLoadString)
        {
            return base.Channel.FindDetailAdv4_TestAsync(login, password, makeLogo, detailNum, substLevel, substFilter, deliveryRegionType, minDeliveryPercentString, maxADDaysString, minQuantityString, maxResultPriceString, maxOneDetailOffersCountString, detailNumsToLoadString);
        }
        
        public System.Threading.Tasks.Task<EmexSrv.SearchResult> FindDetailAdv5_TestAsync(long login, string password, string makeLogo, string detailNum, EmexSrv.SearchSubstLevel substLevel, EmexSrv.SearchSubstFilter substFilter, EmexSrv.FindDeliveryRegionType deliveryRegionType, string minDeliveryPercentString, string maxADDaysString, string minQuantityString, string maxResultPriceString, string maxOneDetailOffersCountString, string detailNumsToLoadString)
        {
            return base.Channel.FindDetailAdv5_TestAsync(login, password, makeLogo, detailNum, substLevel, substFilter, deliveryRegionType, minDeliveryPercentString, maxADDaysString, minQuantityString, maxResultPriceString, maxOneDetailOffersCountString, detailNumsToLoadString);
        }
        
        public System.Threading.Tasks.Task<string> TestConnectAsync(string s)
        {
            return base.Channel.TestConnectAsync(s);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EmExServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.EmExServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EmExServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://ws.emex.ru/EmExService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.EmExServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://ws.emex.ru/EmExService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            EmExServiceSoap,
            
            EmExServiceSoap12,
        }
    }
}
